/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ImpressorasRouteImport } from './routes/impressoras'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AgentesRouteImport } from './routes/agentes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesClientIdRouteImport } from './routes/clientes.$clientId'
import { Route as ClientesClientIdImpressorasPrinterIdRouteImport } from './routes/clientes_.$clientId.impressoras.$printerId'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressorasRoute = ImpressorasRouteImport.update({
  id: '/impressoras',
  path: '/impressoras',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRoute = AgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClientIdRoute = ClientesClientIdRouteImport.update({
  id: '/clientes/$clientId',
  path: '/clientes/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClientIdImpressorasPrinterIdRoute =
  ClientesClientIdImpressorasPrinterIdRouteImport.update({
    id: '/clientes_/$clientId/impressoras/$printerId',
    path: '/clientes/$clientId/impressoras/$printerId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/alertas': typeof AlertasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/impressoras': typeof ImpressorasRoute
  '/relatorios': typeof RelatoriosRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/clientes/$clientId/impressoras/$printerId': typeof ClientesClientIdImpressorasPrinterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/alertas': typeof AlertasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/impressoras': typeof ImpressorasRoute
  '/relatorios': typeof RelatoriosRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/clientes': typeof ClientesIndexRoute
  '/clientes/$clientId/impressoras/$printerId': typeof ClientesClientIdImpressorasPrinterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/alertas': typeof AlertasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/impressoras': typeof ImpressorasRoute
  '/relatorios': typeof RelatoriosRoute
  '/clientes/$clientId': typeof ClientesClientIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/clientes_/$clientId/impressoras/$printerId': typeof ClientesClientIdImpressorasPrinterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentes'
    | '/alertas'
    | '/configuracoes'
    | '/impressoras'
    | '/relatorios'
    | '/clientes/$clientId'
    | '/clientes/'
    | '/clientes/$clientId/impressoras/$printerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentes'
    | '/alertas'
    | '/configuracoes'
    | '/impressoras'
    | '/relatorios'
    | '/clientes/$clientId'
    | '/clientes'
    | '/clientes/$clientId/impressoras/$printerId'
  id:
    | '__root__'
    | '/'
    | '/agentes'
    | '/alertas'
    | '/configuracoes'
    | '/impressoras'
    | '/relatorios'
    | '/clientes/$clientId'
    | '/clientes/'
    | '/clientes_/$clientId/impressoras/$printerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentesRoute: typeof AgentesRoute
  AlertasRoute: typeof AlertasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ImpressorasRoute: typeof ImpressorasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ClientesClientIdRoute: typeof ClientesClientIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ClientesClientIdImpressorasPrinterIdRoute: typeof ClientesClientIdImpressorasPrinterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressoras': {
      id: '/impressoras'
      path: '/impressoras'
      fullPath: '/impressoras'
      preLoaderRoute: typeof ImpressorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes': {
      id: '/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clientId': {
      id: '/clientes/$clientId'
      path: '/clientes/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof ClientesClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes_/$clientId/impressoras/$printerId': {
      id: '/clientes_/$clientId/impressoras/$printerId'
      path: '/clientes/$clientId/impressoras/$printerId'
      fullPath: '/clientes/$clientId/impressoras/$printerId'
      preLoaderRoute: typeof ClientesClientIdImpressorasPrinterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentesRoute: AgentesRoute,
  AlertasRoute: AlertasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ImpressorasRoute: ImpressorasRoute,
  RelatoriosRoute: RelatoriosRoute,
  ClientesClientIdRoute: ClientesClientIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ClientesClientIdImpressorasPrinterIdRoute:
    ClientesClientIdImpressorasPrinterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
